name: release-mariadb-acorn

on:
  push:
    tags:
      - "*/v[0-9]*"

jobs:
  push:
    runs-on: buildjet-4vcpu-ubuntu-2004
    steps:
      - uses: actions/checkout@v3
      - uses: acorn-io/actions-setup@v2
        with:
          acorn-version: main
      - uses: acorn-io/actions-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set image and tag
        run: ./scripts/setup_tags.sh
      - name: Build and push acorn
        run: |
          acorn build --platform linux/amd64 --platform linux/arm64 --push -t ghcr.io/acorn-io/library/${IMAGE}:${TAG} ./${IMAGE}/
          acorn tag ghcr.io/acorn-io/library/${IMAGE}:${TAG} ghcr.io/acorn-io/library/${IMAGE}:latest
          acorn push ghcr.io/acorn-io/library/${IMAGE}:latest
